# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - 'otel-collector:4318'
  
  - job_name: 'webapp'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:7298']
  
  - job_name: 'catalog-api'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5222']

  - job_name: 'identity-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5243']

  - job_name: 'order-processor'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:16888']

  - job_name: 'ordering-api'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5224']

  - job_name: 'payment-processor'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5226']

  - job_name: 'webhooks-api'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5227']

  - job_name: 'webhooksclient'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:7260']  



  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] 
storage:
  tsdb:
    out_of_order_time_window: 30m